name       : python-gast
version    : 0.4.0
release    : 3
source     :
    - https://github.com/serge-sans-paille/gast/archive/0.4.0.tar.gz : 2ae00b3a79c08be613c556c3e8268507cfb6179eb3fd2b59fec58cc792d2e308
license    : BSD-3-Clause
component  : programming.python
summary    : Python AST that abstracts the underlying Python version
description: |
    A generic AST to represent Python2 and Python3's Abstract Syntax Tree(AST).
build      : |
    %python3_setup
install    : |
    %python3_install
