name       : python-gast
version    : 0.5.2
release    : 5
source     :
    - https://github.com/serge-sans-paille/gast/archive/refs/tags/0.5.2.tar.gz : 85f1162c533c1f8f8e0914c7c25ca4875385d6b2043326759404a20eb76ba3f3
license    : BSD-3-Clause
component  : programming.python
summary    : Python AST that abstracts the underlying Python version
description: |
    A generic AST to represent Python2 and Python3's Abstract Syntax Tree(AST).
build      : |
    %python3_setup
install    : |
    %python3_install
