name       : python-gast
version    : 0.5.3
release    : 6
source     :
    - https://github.com/serge-sans-paille/gast/archive/refs/tags/0.5.3.tar.gz : 352db13ff595ffbbfda258ef5bdadbae126bfa7cad1ef27fe25c6243144626b4
license    : BSD-3-Clause
component  : programming.python
summary    : Python AST that abstracts the underlying Python version
description: |
    A generic AST to represent Python2 and Python3's Abstract Syntax Tree(AST).
build      : |
    %python3_setup
install    : |
    %python3_install
